/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as QaIndexRouteImport } from './routes/qa/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PrIndexRouteImport } from './routes/pr/index'
import { Route as MasterIndexRouteImport } from './routes/master/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PrStatusRouteImport } from './routes/pr/status'
import { Route as PrGajanaRouteImport } from './routes/pr/gajana'
import { Route as MasterUsersRouteImport } from './routes/master/users'
import { Route as MasterInactiveUsersRouteImport } from './routes/master/inactive-users'
import { Route as MasterWorkshopsIndexRouteImport } from './routes/master/workshops/index'
import { Route as MasterEventsIndexRouteImport } from './routes/master/events/index'
import { Route as ApiRazorpayIndexRouteImport } from './routes/api/razorpay/index'
import { Route as MasterWorkshopsIdRouteImport } from './routes/master/workshops/$id'
import { Route as MasterEventsIdRouteImport } from './routes/master/events/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMasterDownloadIndexRouteImport } from './routes/api/master/download/index'
import { Route as ApiQaDownloadAttendanceRouteImport } from './routes/api/qa/download/attendance'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const QaIndexRoute = QaIndexRouteImport.update({
  id: '/qa/',
  path: '/qa/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrIndexRoute = PrIndexRouteImport.update({
  id: '/pr/',
  path: '/pr/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterIndexRoute = MasterIndexRouteImport.update({
  id: '/master/',
  path: '/master/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrStatusRoute = PrStatusRouteImport.update({
  id: '/pr/status',
  path: '/pr/status',
  getParentRoute: () => rootRouteImport,
} as any)
const PrGajanaRoute = PrGajanaRouteImport.update({
  id: '/pr/gajana',
  path: '/pr/gajana',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterUsersRoute = MasterUsersRouteImport.update({
  id: '/master/users',
  path: '/master/users',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterInactiveUsersRoute = MasterInactiveUsersRouteImport.update({
  id: '/master/inactive-users',
  path: '/master/inactive-users',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterWorkshopsIndexRoute = MasterWorkshopsIndexRouteImport.update({
  id: '/master/workshops/',
  path: '/master/workshops/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterEventsIndexRoute = MasterEventsIndexRouteImport.update({
  id: '/master/events/',
  path: '/master/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayIndexRoute = ApiRazorpayIndexRouteImport.update({
  id: '/api/razorpay/',
  path: '/api/razorpay/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterWorkshopsIdRoute = MasterWorkshopsIdRouteImport.update({
  id: '/master/workshops/$id',
  path: '/master/workshops/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterEventsIdRoute = MasterEventsIdRouteImport.update({
  id: '/master/events/$id',
  path: '/master/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMasterDownloadIndexRoute = ApiMasterDownloadIndexRouteImport.update({
  id: '/api/master/download/',
  path: '/api/master/download/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQaDownloadAttendanceRoute = ApiQaDownloadAttendanceRouteImport.update({
  id: '/api/qa/download/attendance',
  path: '/api/qa/download/attendance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/master/inactive-users': typeof MasterInactiveUsersRoute
  '/master/users': typeof MasterUsersRoute
  '/pr/gajana': typeof PrGajanaRoute
  '/pr/status': typeof PrStatusRoute
  '/admin': typeof AdminIndexRoute
  '/master': typeof MasterIndexRoute
  '/pr': typeof PrIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/qa': typeof QaIndexRoute
  '/register': typeof RegisterIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/master/events/$id': typeof MasterEventsIdRoute
  '/master/workshops/$id': typeof MasterWorkshopsIdRoute
  '/api/razorpay': typeof ApiRazorpayIndexRoute
  '/master/events': typeof MasterEventsIndexRoute
  '/master/workshops': typeof MasterWorkshopsIndexRoute
  '/api/qa/download/attendance': typeof ApiQaDownloadAttendanceRoute
  '/api/master/download': typeof ApiMasterDownloadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/master/inactive-users': typeof MasterInactiveUsersRoute
  '/master/users': typeof MasterUsersRoute
  '/pr/gajana': typeof PrGajanaRoute
  '/pr/status': typeof PrStatusRoute
  '/admin': typeof AdminIndexRoute
  '/master': typeof MasterIndexRoute
  '/pr': typeof PrIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/qa': typeof QaIndexRoute
  '/register': typeof RegisterIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/master/events/$id': typeof MasterEventsIdRoute
  '/master/workshops/$id': typeof MasterWorkshopsIdRoute
  '/api/razorpay': typeof ApiRazorpayIndexRoute
  '/master/events': typeof MasterEventsIndexRoute
  '/master/workshops': typeof MasterWorkshopsIndexRoute
  '/api/qa/download/attendance': typeof ApiQaDownloadAttendanceRoute
  '/api/master/download': typeof ApiMasterDownloadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/master/inactive-users': typeof MasterInactiveUsersRoute
  '/master/users': typeof MasterUsersRoute
  '/pr/gajana': typeof PrGajanaRoute
  '/pr/status': typeof PrStatusRoute
  '/admin/': typeof AdminIndexRoute
  '/master/': typeof MasterIndexRoute
  '/pr/': typeof PrIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/qa/': typeof QaIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/master/events/$id': typeof MasterEventsIdRoute
  '/master/workshops/$id': typeof MasterWorkshopsIdRoute
  '/api/razorpay/': typeof ApiRazorpayIndexRoute
  '/master/events/': typeof MasterEventsIndexRoute
  '/master/workshops/': typeof MasterWorkshopsIndexRoute
  '/api/qa/download/attendance': typeof ApiQaDownloadAttendanceRoute
  '/api/master/download/': typeof ApiMasterDownloadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
    | '/master/inactive-users'
    | '/master/users'
    | '/pr/gajana'
    | '/pr/status'
    | '/admin'
    | '/master'
    | '/pr'
    | '/profile'
    | '/qa'
    | '/register'
    | '/tickets'
    | '/api/auth/$'
    | '/master/events/$id'
    | '/master/workshops/$id'
    | '/api/razorpay'
    | '/master/events'
    | '/master/workshops'
    | '/api/qa/download/attendance'
    | '/api/master/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
    | '/master/inactive-users'
    | '/master/users'
    | '/pr/gajana'
    | '/pr/status'
    | '/admin'
    | '/master'
    | '/pr'
    | '/profile'
    | '/qa'
    | '/register'
    | '/tickets'
    | '/api/auth/$'
    | '/master/events/$id'
    | '/master/workshops/$id'
    | '/api/razorpay'
    | '/master/events'
    | '/master/workshops'
    | '/api/qa/download/attendance'
    | '/api/master/download'
  id:
    | '__root__'
    | '/'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
    | '/master/inactive-users'
    | '/master/users'
    | '/pr/gajana'
    | '/pr/status'
    | '/admin/'
    | '/master/'
    | '/pr/'
    | '/profile/'
    | '/qa/'
    | '/register/'
    | '/tickets/'
    | '/api/auth/$'
    | '/master/events/$id'
    | '/master/workshops/$id'
    | '/api/razorpay/'
    | '/master/events/'
    | '/master/workshops/'
    | '/api/qa/download/attendance'
    | '/api/master/download/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  MasterInactiveUsersRoute: typeof MasterInactiveUsersRoute
  MasterUsersRoute: typeof MasterUsersRoute
  PrGajanaRoute: typeof PrGajanaRoute
  PrStatusRoute: typeof PrStatusRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MasterIndexRoute: typeof MasterIndexRoute
  PrIndexRoute: typeof PrIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  QaIndexRoute: typeof QaIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  MasterEventsIdRoute: typeof MasterEventsIdRoute
  MasterWorkshopsIdRoute: typeof MasterWorkshopsIdRoute
  ApiRazorpayIndexRoute: typeof ApiRazorpayIndexRoute
  MasterEventsIndexRoute: typeof MasterEventsIndexRoute
  MasterWorkshopsIndexRoute: typeof MasterWorkshopsIndexRoute
  ApiQaDownloadAttendanceRoute: typeof ApiQaDownloadAttendanceRoute
  ApiMasterDownloadIndexRoute: typeof ApiMasterDownloadIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/': {
      id: '/qa/'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pr/': {
      id: '/pr/'
      path: '/pr'
      fullPath: '/pr'
      preLoaderRoute: typeof PrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/': {
      id: '/master/'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pr/status': {
      id: '/pr/status'
      path: '/pr/status'
      fullPath: '/pr/status'
      preLoaderRoute: typeof PrStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pr/gajana': {
      id: '/pr/gajana'
      path: '/pr/gajana'
      fullPath: '/pr/gajana'
      preLoaderRoute: typeof PrGajanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/users': {
      id: '/master/users'
      path: '/master/users'
      fullPath: '/master/users'
      preLoaderRoute: typeof MasterUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/inactive-users': {
      id: '/master/inactive-users'
      path: '/master/inactive-users'
      fullPath: '/master/inactive-users'
      preLoaderRoute: typeof MasterInactiveUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/workshops/': {
      id: '/master/workshops/'
      path: '/master/workshops'
      fullPath: '/master/workshops'
      preLoaderRoute: typeof MasterWorkshopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/events/': {
      id: '/master/events/'
      path: '/master/events'
      fullPath: '/master/events'
      preLoaderRoute: typeof MasterEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/': {
      id: '/api/razorpay/'
      path: '/api/razorpay'
      fullPath: '/api/razorpay'
      preLoaderRoute: typeof ApiRazorpayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/workshops/$id': {
      id: '/master/workshops/$id'
      path: '/master/workshops/$id'
      fullPath: '/master/workshops/$id'
      preLoaderRoute: typeof MasterWorkshopsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/events/$id': {
      id: '/master/events/$id'
      path: '/master/events/$id'
      fullPath: '/master/events/$id'
      preLoaderRoute: typeof MasterEventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/master/download/': {
      id: '/api/master/download/'
      path: '/api/master/download'
      fullPath: '/api/master/download'
      preLoaderRoute: typeof ApiMasterDownloadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qa/download/attendance': {
      id: '/api/qa/download/attendance'
      path: '/api/qa/download/attendance'
      fullPath: '/api/qa/download/attendance'
      preLoaderRoute: typeof ApiQaDownloadAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  MasterInactiveUsersRoute: MasterInactiveUsersRoute,
  MasterUsersRoute: MasterUsersRoute,
  PrGajanaRoute: PrGajanaRoute,
  PrStatusRoute: PrStatusRoute,
  AdminIndexRoute: AdminIndexRoute,
  MasterIndexRoute: MasterIndexRoute,
  PrIndexRoute: PrIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  QaIndexRoute: QaIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  MasterEventsIdRoute: MasterEventsIdRoute,
  MasterWorkshopsIdRoute: MasterWorkshopsIdRoute,
  ApiRazorpayIndexRoute: ApiRazorpayIndexRoute,
  MasterEventsIndexRoute: MasterEventsIndexRoute,
  MasterWorkshopsIndexRoute: MasterWorkshopsIndexRoute,
  ApiQaDownloadAttendanceRoute: ApiQaDownloadAttendanceRoute,
  ApiMasterDownloadIndexRoute: ApiMasterDownloadIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
